# Generated by Django 5.1.1 on 2024-10-03 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListingCountry',
            new_name='Country',
        ),
        migrations.RenameModel(
            old_name='ListingState',
            new_name='State',
        ),
    ]
