# Generated by Django 5.1.1 on 2024-10-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_insight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingcategory',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='Listing Category'),
        ),
    ]
