# Generated by Django 5.1.1 on 2024-10-12 09:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_alter_listingcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingcategory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listingcategory',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
