# Generated by Django 4.2.5 on 2024-10-31 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0009_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insight',
            name='user',
        ),
        migrations.AddField(
            model_name='insight',
            name='category',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insight',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
