# Generated by Django 4.2.5 on 2024-11-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0011_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='manufacturer',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default=1, max_length=25),
            preserve_default=False,
        ),
    ]
